server:
  port: 8080
spring:
  datasource:
    url: "jdbc:mysql://101.43.17.240:3306/javaee?useUnicode=true&characterEncoding=utf-8"
    username: "root"
    password: "oxyay"
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath*:Mapper/*.xml